name: MDS_Group37
channels:
  - conda-forge
  - defaults
dependencies:
  # core relies
  - python=3.11.6
  - pandas=2.1.2
  - scikit-learn=1.3.2
  - altair=5.1.2  # 保持 5.1.2，但 altair_ally 通常兼容 5.x 版本
  
  # plotting relies
  - vegafusion=1.4.3
  - vegafusion-jupyter=1.4.3
  - vegafusion-python-embed=1.4.3
  - vl-convert-python=1.0.1
  
  # jupyter
  - ipykernel=6.26.0
  - requests=2.31.0
  - notebook=6.5.4
  - jupyter_contrib_nbextensions=0.7.0
  
  - click=8.3.1 # Milestone 3

  - pip 
  # altair_ally
  - pip:
    - altair_ally>=0.1.1
    - ucimlrepo
    - "deepchecks[tabular]"
    - anywidget